### ISSUE TITLE
定性的一个问题

### ISSUE THREAD

**Issue by niuyoudaode** [unknownue/pdflow#1]
您好，请问那个定性结果里面的渐变颜色是怎么生成的（The color of each point indicates its reconstruction error measured by P2M distance.）

**Comment by unknownue** [comment]
Here are some projects to help you rendering point cloud:
- [Structurenet](https://github.com/daerduoCarey/structurenet)
- [PointFlowRenderer](https://github.com/zekunhao1995/PointFlowRenderer)

To support rendering independent color for each point, you need to:
1. Normalize the P2M distance to range [0, 1]
2. Convert the normalized distance to color value by matplotlib and save them to a rgb file
3. Modify the above rendering script to read rgb file and assign color to each point when rendering
