### ISSUE TITLE
Problem with instalation

### ISSUE THREAD

**Issue by Siziff** [unknownue/pdflow#4]
Hello everyone, I can't run the training, writes about the absence of some files. I checked all the libraries, they are on my computer + I arranged the training data as follows. What could be the matter ? Why is my training not starting ?

![image](https://user-images.githubusercontent.com/42972554/201655709-82b58cf4-6174-42a3-bc95-b08ba06326dc.png) 

![image](https://user-images.githubusercontent.com/42972554/201656321-9ec961d3-cb64-4cc7-b38a-0fdd86f38f55.png)

**Comment by unknownue** [comment]
Probably due to using incompatible versions of pytorch and cuda.
Just use the exact same version of pytorch and cuda mentioned in README, and you will good to go.
If you want not to change the environment on your machine, just try docker.
